### ISSUE TITLE
When :seen? dispatch not firing

### ISSUE THREAD

**Issue by colindresj** [Day8/re-frame-async-flow-fx#1]
Giving the async flow a try out for app boot, but hoping to use the pattern more generally in the future. Right now I've got the following:

```clj
(reg-event-fx
  :init-app
  (fn [_ _]
    {:db {}
     :async-flow
     {:id :flow/init-app
      :first-dispatch [:do-token-get]
      :rules [
        {:when :seen? :events :success-token-get :dispatch [:do-user-get]}
        {:when :seen? :events :success-user-get :dispatch [:success-boot] :halt? true}
        {:when :seen? :events :fail-user-get :dispatch [:fail-boot] :halt? true}]}}))
```

The `:do-token-get` event is firing off fine, as well as the the `:success-token-get`. However, `:do-user-get` never happens, which, of course, causes the rest of the flow to not occur.

Am I missing something here?

**Comment by hipitihop** [comment]
On the surface that looks fine.
1. Could you please include your project deps so we can confirm re-frame and fx versions.
2. The `:do-user-get` handler must be defined (otherwise you will see a re-frame error telling you it is being ignored) in which case it never gets dispatched.

**Comment by colindresj** [comment]
Ah, bumping to `0.0.5` fixed it for me. Didn't realize there was a `develop` branch. Thanks @hipitihop
