### ISSUE TITLE
Is it possible to pass the results of :first-dispatch to :rules?

### ISSUE THREAD

**Issue by deadghost** [Day8/re-frame-async-flow-fx#11]
For example, I make a http request for widget data and want to use `(:owner widget)` in more http requests in my `:rules`.

**Comment by hipitihop** [comment]
@deadghost  PR #20 has now been merged which support for dispatch-fn see ["Advanced use"](https://github.com/Day8/re-frame-async-flow-fx#advanced-use) in readme. This should address your use case, Closing.
