### ISSUE TITLE
[feature request] Make :first-dispatch optional?

### ISSUE THREAD

**Issue by iku000888** [Day8/re-frame-async-flow-fx#12]
Thanks for this useful library.

I ran into a usecase where I definitely want to use this to wait for the completion of several concurrent events that does not have a concrete initiator. and thought it would be nice to make :first-dispatch optional.

Just throwing this out there, and have not thought through whether more people would shoot their own foot or not in this case.

**Comment by mudgen** [comment]
I also would like first-dispatch to be optional.  Currently I am forced to use it when it is not needed for my application. I am merely using this library to trigger some events when other events occur.
