### ISSUE TITLE
Discrepancy with re-frame API in terms of event IDs

### ISSUE THREAD

**Issue by p-himik** [Day8/re-frame-async-flow-fx#16]
Documentation of `reg-event-db` and `reg-event-fx` says: `id is typically a namespaced keyword  (but can be anything)`. So, it can be an `ICollection`, but in order for such event IDs to work with `re-frame-async-flow-fx`, they have to be wrapped in yet another collection.

**Comment by danielcompton** [comment]
> So, it can be an ICollection, but in order for such event IDs to work with re-frame-async-flow-fx, they have to be wrapped in yet another collection.

Can you give a concrete example of the problem you're running in to? I'm not quite sure what wrapping the event in a collection would do?

**Comment by p-himik** [comment]
Yeah, you're right, because of how `as-callback-pred` works, I'll have to provide full event vector for non-keyword IDs to work.

There's no concrete example, at least not yet. I was just experimenting with different patterns of how one would write complex reusable components with `re-frame`, and I already use vectors and event IDs in some places, so I noticed this discrepancy and decided to report it.

**Comment by hipitihop** [comment]
As there seems nothing to action at this point, closing.
