### ISSUE TITLE
Add a timeout to boot flow

### ISSUE THREAD

**Issue by danielcompton** [Day8/re-frame-async-flow-fx#2]
A good general principle for asynchronous operations is to set a timeout to make sure you don't wait forever. Here is suggested syntax that extends boot flow:

```clj
(defn boot-flow
  []
  {:first-dispatch [:do-X]              ;; what event kicks things off ?
   ;; New timeout key
   :timeout [{:ms 30000
              :dispatch [::boot-timeout]
   :rules [                             ;; a set of rules describing the required flow
     {:when :seen? :events :success-X  :dispatch [:do-Y]}
     {:when :seen? :events :success-Y  :dispatch [:do-Z]}
     {:when :seen? :events :success-Z  :halt? true}
      ;; Added new failure event
     {:when :seen-any-of? :events [:fail-X :fail-Y :fail-Z ::boot-timeout] :dispatch  [:app-failed-state] :halt? true}]})
```

The way this feature would work is that you would provide a vector of maps with an `:ms` timeout, and a `:dispatch` event (this is the same as `:dispatch-later`). If the app were still booting after the specified number of milliseconds, then the dispatch would be called. 

A timeout doesn't trigger a halting of the boot sequence by itself; it still needs to weave back into the rest of the boot flow.

Use cases for this:

* Fail when operations take too long to complete
* If it is taking longer than expected for the boot flow to finish then update the user with a message: "This is taking a bit longer than expected..."

**Comment by mike-thompson-day8** [comment]
This would be useful. Let's do a PR.

**Comment by hipitihop** [comment]
I have taken a first shot in branch [flow-timeout-#2](https://github.com/Day8/re-frame-async-flow-fx/commit/443bae7a4c2015fef275b0c7b4f028a5797be4ab) which is an arguably naive implementation  leveraging :dispatch-later but I have these observations which some may wish to add their 2 cents to

Observations:
- using :dispatch-later provides no facility to cancel the timeout(s)
  so in turn the timeout will unconditionally fire, with no trivial
  way for the handler to know if the flow completed or not without
  maintaining its own state. A better impl would be to hang on to
   the timeouts and cancel them on flow halt.
- assuming we do keep cancelable timeout refs, this may need to leak
  js object refs into dp-path and/or events, some might find this a smell
- using js/timeout is not compatible with JVM even with
  re-frame.interop/set-timeout! as the JVM implementation just fires fn.

**Comment by hipitihop** [comment]
After further review, we feel that without inventing use-cases, async timeout issues should be handled at the individual flow event/rule rather then some flow global timeout e.g. if you are coordinating multiple ajax calls via https://github.com/JulianBirch/cljs-ajax, that supports :timeout as do other async operations/libs, so it is up to your events lusing these libs to instrument those timeouts and dispatch appropriate events so that your flow rules can decide what to do when one or more of them timeout. Closing
