### ISSUE TITLE
Cut a release and/or deps.edn?

### ISSUE THREAD

**Issue by lwhorton** [Day8/re-frame-async-flow-fx#24]
Hello,

I know this project is fairly stable and that the authors don't have much time on their hands. That being said, a few days ago some pretty significant changes went into place (`dispatch-fn` and removing the need for `first-dispatch`). When can we expect a `0.0.11` release + push to clojars? 

In a related vein, maybe this project should utilize `deps.edn` so others can consume the lib via the deps/cli `:git/url` target. This would obviate the need to wait on an author's release before consumers could act on newer features. Thoughts?

**Comment by hipitihop** [comment]
0.0.11 Released
