### ISSUE TITLE
How do I trigger `re-frame/reg-fx` with this library?

### ISSUE THREAD

**Issue by Invertisment** [day8/re-frame-async-flow-fx#35]
I'm new to re-frame and I want to control a pipeline of promises.

I think this library allows to do it but it requires to register EVent handlers for each action and I want to use EFfects.
I think that using EFfects is better as they don't mutate the application state and instead trigger EFfects which I'd like to listen to.

The tutorial of re-frame tells that EFfects are what should be used mutations (outside world, data fetching, etc.) and EVents (the ones who are triggered via `dispatch`) should be used to process user's callbacks and change application's state.
This is the doc: https://day8.github.io/re-frame/Effects/.

I'd like to know what is the best way to use this library if I want to fire several consecutive EFfects which do some fetching. The original re-frame tutorial doesn't show any example which deals with execution of two consecutive requests, for instance.

I think I simply need an example because I can't think of a better way than to wrap every step of my logic into a EVent handler that requests EFfects to happen. Is this the way to do it?
(By "wrap" I mean to have an EVent that simply returns cofx that triggers one or multiple EFfects)

**Comment by mike-thompson-day8** [comment]
Issues are for bugs and feature requests. 

Best to get tutorial help via slack or Github's discussions feature:
[![Get help on Slack](http://img.shields.io/badge/slack-clojurians%20%23re--frame-97C93C?labelColor=283C67&logo=slack&style=for-the-badge)](https://clojurians.slack.com/channels/re-frame)

You might be interested to have a look at the `re-frame-http-fx` library which has to initiate async actions and then handle success or failure.
