### ISSUE TITLE
Include upgraded deps versions in CHANGELOG

### ISSUE THREAD

**Issue by srwiseman** [day8/re-frame-async-flow-fx#37]
Incredibly minor.

However, when auditing library changes, it's very convenient to see the exact upgraded deps versions in the changelogs of the libraries instead of "Update deps to including latest clojure, clojurescript & shadow-cljs".

Listing the upgraded deps versions on the changelog would also be consistent with other re-frame libraries.

I can provide a PR to the changelog later today if I get time.

**Comment by hipitihop** [comment]
Will include in future changes. Thanks. See 0.4.0
